# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    #esi:             ~
    translator:      { fallback: '%locale%' }
    secret: '%secret%'
    csrf_protection: true
    #http_method_override: true
    router:
        resource: "%kernel.root_dir%/config/packages/routing.yml"
        strict_requirements: '%kernel.debug%'
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  '%locale%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"

    #esi: true
    #fragments: true
    php_errors:
        log: true
