twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        warning_load_level: '%env(WARNING_LOAD_LEVEL)%'
        url_prefix: '%env(URL_PREFIX)%'
